formats:
    #default format *MUST* be present
    default:
        width: 800
        height: 800
    thumb:
        width: 150
        height: 150
prepared_images:
    #method is one of choose, gd, gmagick, imagick
    method: choose
    path: /var/www/prepared_images/
iip:
    server: /iipsrv
ui:
    enable_right_click: true
roots:
    - /var/www/images
